---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-dev-cjsm-tls
  namespace: cjsm-dev
spec:
  secretName: www-dev-cjsm-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - www.dev.cjsm.justice.gov.uk