---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-prod-cjsm-tls
  namespace: cjsm-prod
spec:
  secretName: www-prod-cjsm-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - www.cjsm.justice.gov.uk