# redirect from www.cjsm.justice.gov.uk to cjsm.justice.gov.uk
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cjsm-prod-www-prod-redirect
  namespace: cjsm-prod
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: cjsm-prod-www-prod-redirect-cjsm-prod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/permanent-redirect: https://cjsm.justice.gov.uk/
spec:
  ingressClassName: modsec
  tls:
  - hosts:
      - www.cjsm.justice.gov.uk
    secretName: www-prod-cjsm-tls
  rules:
  - host: www.cjsm.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: dunno-service
            port: 
              number: 4567
